#In this script it is important to set the RepositoryUrl in the *.csproj file
#<PropertyGroup>
#  ...
#  <PackageProjectUrl>https://github.com/michaelroth1/homeNet.Components</PackageProjectUrl>
#  <RepositoryUrl>https://github.com/michaelroth1/homeNet.Components</RepositoryUrl>
#</PropertyGroup>

name: NuGet Generation for mitoSoft.Common.Webcam

on:
  push:
    #branches:
      #- main
    tags:
      - "v*"
  workflow_dispatch:
    
env:
  SOURCE_URL: https://api.nuget.org/v3/index.json
  PROJECT_FILE: mitoSoft.Common.Webcam.csproj
  PROJECT_FOLDER: mitoSoft.Common.Webcam
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: getversion
        uses: actions/github-script@v5
        with:
          script: |
            const version = "${{ github.ref }}".split('/')[2].replace('v','').replace('V','').replace('version','').replace('Version','')
            core.setOutput('version', version)
            
      - run: echo "${{steps.getversion.outputs.version}}"

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          #version is optional: without means latest
          dotnet-version: 6.0.x 
          source-url: ${{env.SOURCE_URL}}  
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}        
          
      - name: Build solution and generate NuGet package
        run: dotnet build ${{ env.PROJECT_FOLDER }}/${{ env.PROJECT_FILE }} -c Release /p:Version=${{steps.getversion.outputs.version}}      
          
      - name: Push generated package to Nuget.org
        run: dotnet nuget push ./${{env.PROJECT_FOLDER}}/bin/Release/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source "${{env.SOURCE_URL}}" --skip-duplicate --no-symbols
